config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  resources :users, only: %i[show edit update destroy]
  resources :posts, only: %i[index show new create destroy] do
    resource :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :pasas, only: %i[index show] do
    get '/autocomplete_facility/:facility', on: :collection, action: :autocomplete_facility
  end
  
  resources :genres, only: %i[index]
  get 'gourmet' => 'genres#gourmet'
  get 'toilet' => 'genres#toilet'
  get 'smoking' => 'genres#smoking'
  get 'search' => 'searches#search'
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts

  enum genre: {
    "--ジャンル選択--": 0, グルメ: 1, トイレ: 2, 喫煙所: 3
  }
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def gourmet
    @genre = Genre.find(1)
    @posts = @genre.posts.page(params[:page]).per(12)
  end

  def toilet
    @genre = Genre.find(2)
    @posts = @genre.posts.page(params[:page]).per(12)
  end

  def smoking
    @genre = Genre.find(3)
    @posts = @genre.posts.page(params[:page]).per(12)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/gourmet.html.erb
<%= render 'layouts/header' %>

<h2 class="heading col-md-4 mt-3">ジャンル：グルメ</h2>

<div class="row">
  <% @posts.each do |post| %>
    <div class="posts col-md-3">
      <div class="one-post">
        <%= link_to post_path(post.id) do %>
          <h3 class="title">
            <%= post.title %>
          </h3>
          <div class="image">
            <%= attachment_image_tag post, :image, format: 'jpeg', fallback: "noimage2.jpg", size:'240x160', class: "image" %>
          </div>
          
          <div class="name-favorite">
            <%= attachment_image_tag post.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:'40x40', class: "profileimage-circle" %>
            <%= post.user.nickname %>/
            ♥<%= post.favorites.count %> いいね
          </div>
          
          <div class="created_at">
              投稿日：<%= post.created_at.strftime('%Y/%m/%d') %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
  
  <%= paginate @posts %>
  <%= render 'layouts/footer' %>

app/views/genres/index.html.erb
<%= stylesheet_link_tag 'genres', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= render 'layouts/header' %>
  <h2 class="heading col-md-3 m-3">ジャンル一覧</h2>
  
  <div class="pasanavi_about-detail">
    <div class="genres">
      
      <div class="food">
        <%= link_to gourmet_path do %>
          <div class="genre-text"><i class="fas fa-utensils"></i>グルメ</div>
          <div class="food-image"></div>
        <% end %>
      </div>
      
      <div class="toilet">
        <%= link_to toilet_path do %>
          <div class="genre-text"><i class="fas fa-toilet"></i>トイレ</div>
          <div class="toilet-image"></div>
        <% end %>
      </div>
      
      <div class="smoking">
        <%= link_to smoking_path do %>
          <div class="genre-text"><i class="fas fa-smoking"></i>喫煙所</div>
          <div class="smoking-image"></div>
        <% end %>
      </div>
      
    </div>
  </div>
<%= render 'layouts/footer' %>

app/views/genres/smoking.html.erb
<%= render 'layouts/header' %>

<h2 class="heading col-md-3 mt-3">ジャンル：喫煙所</h2>
<div class="row">
  <% @posts.each do |post| %>
    <div class="posts col-md-3">
      <div class="one-post">
        <%= link_to post_path(post.id) do %>
        
          <h3 class="title">
            <%= post.title %>
          </h3>
          
          <div class="image">
            <%= attachment_image_tag post, :image, format: 'jpeg', fallback: "noimage2.jpg", size:'240x160', class: "image" %>
          </div>
          
          <div class="name-favorite">
            <%= attachment_image_tag post.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:'40x40', class: "profileimage-circle" %>
            <%= post.user.nickname %>/
            ♥<%= post.favorites.count %> いいね
          </div>
          
          <div class="created_at">
              投稿日：<%= post.created_at.strftime('%Y/%m/%d') %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<%= paginate @posts %>
<%= render 'layouts/footer' %>

app/views/genres/toilet.html.erb
<%= render 'layouts/header' %>

<h2 class="heading col-md-3 mt-3">ジャンル：トイレ</h2>
<div class="row">
  <% @posts.each do |post| %>
    <div class="posts col-md-3">
      <div class="one-post">
        <%= link_to post_path(post.id) do %>
        
          <h3 class="title">
            <%= post.title %>
          </h3>
          
          <div class="image">
            <%= attachment_image_tag post, :image, format: 'jpeg', fallback: "noimage2.jpg", size:'240x160', class: "image" %>
          </div>
          
          <div class="name-favorite">
            <%= attachment_image_tag post.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:'40x40', class: "profileimage-circle" %>
            <%= post.user.nickname %>/
            ♥<%= post.favorites.count %> いいね
          </div>
          
          <div class="created_at">
              投稿日：<%= post.created_at.strftime('%Y/%m/%d') %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<%= paginate @posts %>
<%= render 'layouts/footer' %>