config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  resources :users, only: %i[show edit update destroy]
  resources :posts, only: %i[index show new create destroy] do
    resource :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :pasas, only: %i[index show] do
    get '/autocomplete_facility/:facility', on: :collection, action: :autocomplete_facility
  end
  
  resources :genres, only: %i[index]
  get 'gourmet' => 'genres#gourmet'
  get 'toilet' => 'genres#toilet'
  get 'smoking' => 'genres#smoking'
  get 'search' => 'searches#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  attachment :profile_image

  validates :name, presence: true
  validates :nickname, presence: true
  validates :email, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @posts = @user.posts
  end

  def edit
    @user = current_user
    redirect_to user_path(current_user.id) unless current_user.id == @user.id
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = 'ユーザー情報を更新しました。.'
      redirect_to user_path(current_user.id)
    else
      render action: :edit
    end
  end

  def destroy
    @user = current_user
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :nickname, :email, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="container">
  <div class="row">
    <h2 class="heading col-md-5 m-3">ユーザー情報変更</h2>
    <div class="col-lg-12 mx-auto">
      
      <div class="errors">
        <% if @user.errors.any? %>
          <%= @user.errors.count %>つのエラー:
          <% @user.errors.full_messages.each do |message| %><br>
            <%= message %>
          <% end %>
        <% end %>
      </div>

        <%= form_with model:@user, local:true do |f| %>

          <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'200x200' %>
  
          <div class="form-group">
            <label for ="user-image"></label>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </div>
  
          <div class="form-group">
            <label for ="user-name">氏名</label>
            <%= f.text_field :name, autofocus: true, class: "form-control", id:"inputName", placeholder:"名前"%>
          </div>
  
          <div class="form-group">
            <label for ="user-name">ニックネーム</label>
            <%= f.text_field :nickname, autofocus: true, class: "form-control", id:"inputnickName", placeholder:"ニックネーム"%>
          </div>
  
  
  
          <div class="form-group">
            <label for ="user-email">メールアドレス</label>
            <%= f.text_area :email, autofocus: true, class: "form-control", id:"email"%>
          </div>
  
          <%= f.submit "更新", class: "btn btn-success" %>
        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= render 'layouts/header' %>

<% if notice %>
　　<p id="notice"><%= notice %></p>
<% end %>

  <h2 class="heading col-md-3 m-3">マイページ</h2>

  <div class="col-lg-3">
    <div class="user-info">
      <div class="profile-container m-3">
       <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100', class: "profileimage-circle" %>
      </div>
      
      <div class="user-name">
        <p>氏名</p>
        <h3><%= @user.name %></h3>
      </div>

      <div class="user-nickname">
        <p>ニックネーム（表示名)</p>
        <h3><%= @user.nickname %></h3>
      </div>

      <div class="user-email">
        <p>メールアドレス</p>
        <h3><%= @user.email %></h3>
      </div>

      <div class="user-edit-btn">
        <%= link_to edit_user_path(@user.id), class: 'btn btn-block btn btn-outline-secondary' do %><i class="fas fa-user-cog" aria-hidden="true"></i><% end %>
        <%= link_to 'アカウントの削除', user_path(@user.id), method: :delete, data: { confirm: 'アカウントを本当に消去しますか?' }, class: "btn btn-block btn-danger" %>
      </div>
    </div>
  </div>

  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-md-3 m-3">
        <div class="one-post">
          <%= link_to post_path(post.id) do %>
            <h3 class="title">
              <%= post.title %>
            </h3>

            <div class="image">
              <%= attachment_image_tag post, :image, format: 'jpeg', fallback: "noimage2.jpg", size:'240x160', class: "image" %>
            </div>

            <div class="name-favorite">
              <%= post.user.nickname %>/
              ♥<%= post.favorites.count %> いいね
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<%= render 'layouts/footer' %>