config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  resources :users, only: %i[show edit update destroy]
  resources :posts, only: %i[index show new create destroy] do
    resource :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :pasas, only: %i[index show] do
    get '/autocomplete_facility/:facility', on: :collection, action: :autocomplete_facility
  end
  
  resources :genres, only: %i[index]
  get 'gourmet' => 'genres#gourmet'
  get 'toilet' => 'genres#toilet'
  get 'smoking' => 'genres#smoking'
  get 'search' => 'searches#search'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    search = params[:search]
    word = params[:word]
    @word = params[:word]

    if @range == 'pasa'
      @pasa = Pasa.search(search, word)
    else
      @post = Post.search(search, word)
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searches/search.html.erb
<%= render 'layouts/header' %>
<h2>検索結果：<%= @word %></h2>
<% if @range == 'pasa' %>
　<table class="table table-hover table-inverse">

      <thead>
        <tr>
         <th>PA/SA名</th>
         <th>都道府県</th>
         <th>高速道路</th>
        </tr>
      </thead>

      <tbody>
         <% @pasa.each do |pasa| %>
         <tr>
          <td>
           <%= link_to pasa.facility, pasa_path(pasa.id) %>
          </td>
          <td><%= pasa.prefecture %></td>
          <td><%= pasa.highway_name %></td>
         </tr>
         <% end %>
      </tbody>

  </table>

<% else %>
  <div class="row">
    <% @post.each do |post| %>
      <div class="col-md-3 mt-3">
        <div class="one-post">
          <%= link_to post_path(post.id) do %>
            <h3 class="title">
              <%= post.title %>
            </h3>

            <div class="image">
              <%= attachment_image_tag post, :image, format: 'jpeg', fallback: "no_image.jpg", size:'240x160', class: "image" %>
            </div>

            <div class="name-favorite">
              <%= attachment_image_tag post.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:'40x40', class: "profileimage-circle" %>
              <%= post.user.name %>/
              ♥<%= post.favorites.count %> いいね
            </div>

            <div class="post-jenre">
              ジャンル：<%= post.genre.name %>
            </div>

            <div class="created_at">
              投稿日：<%= post.created_at.strftime('%Y/%m/%d') %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>