config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  resources :users, only: %i[show edit update destroy]
  resources :posts, only: %i[index show new create destroy] do
    resource :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :pasas, only: %i[index show] do
    get '/autocomplete_facility/:facility', on: :collection, action: :autocomplete_facility
  end
  
  resources :genres, only: %i[index]
  get 'gourmet' => 'genres#gourmet'
  get 'toilet' => 'genres#toilet'
  get 'smoking' => 'genres#smoking'
  get 'search' => 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts

  enum genre: {
    "--ジャンル選択--": 0, グルメ: 1, トイレ: 2, 喫煙所: 3
  }
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/pasa.rb
class Pasa < ApplicationRecord
  has_many :posts

  def self.search(search, word)
    @pasa = if search == 'forward_match'
              Pasa.where('facility LIKE?', "#{word}%")
            elsif search == 'backward_match'
              Pasa.where('facility LIKE?', "%#{word}")
            elsif search == 'perfect_match'
              Pasa.where(word.to_s)
            elsif search == 'partial_match'
              Pasa.where('facility LIKE?', "%#{word}%")
            else
              Pasa.all
            end
  end

  scope :by_facility_like, lambda { |facility|
    where('facility LIKE :value', { value: "#{sanitize_sql_like(facility)}%" })
  }

  enum prefecture: {
    "--都道府県選択--": 0, 北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
    茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
    新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
    岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
    滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
    徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
    福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46, 沖縄県: 47
  }

  enum highway_name: {
    "--高速道路選択--": 0, 道央自動車道: 1, 札樽自動車道: 2, 道東自動車道: 3, 東北自動車道: 4, 八戸自動車道: 5,
    秋田自動車道: 6, 山形自動車道: 7, 磐越自動車道: 8, 日本海東北自動車道: 9, 東北中央自動車道: 10, 北陸自動車道: 11, 東京外環自動車道: 12, 関越自動車道: 13, 上信越自動車道: 14, 長野自動車道: 15,
    常磐自動車道: 16, 館山自動車道: 17, 東関東自動車道: 18, 北関東自動車道: 19, 京葉道路: 20, 富津館山道路: 21, 首都圏中央連絡自動車道: 22, 千葉東金道路: 23, 第三京浜道路: 24, 横浜新道: 25,
    横浜横須賀道路: 26, 東京湾アクアライン・東京湾アクアライン連絡道: 27, 中央自動車道: 28, 中部横断自動車道: 29, 東名高速道路: 30, 新東名高速道路: 31, 名神高速道路: 32, 新名神高速道路: 33, 東海北陸自動車道: 34,
    伊勢湾岸自動車道: 35, 東名阪自動車道: 36, 伊勢自動車道: 37, 紀勢自動車道: 38, 舞鶴若狭自動車道: 39, 東海環状自動車道: 40, 西湘バイパス: 41, 小田原厚木道路: 42,
    西名阪自動車道: 43, 近畿自動車道: 44, 阪和自動車道: 45, 中国自動車道: 46, 山陽自動車道: 47, 岡山自動車道: 48, 米子自動車道: 49,
    松江自動車道: 50, 広島自動車道: 51, 浜田自動車道: 52, 山陰自動車道: 53, 徳島自動車道: 54, 松山自動車道: 55, 高松自動車道: 56, 高知自動車道: 57, 関門橋: 58,
    九州自動車道: 59, 宮崎自動車道: 60, 長崎自動車道: 61, 大分自動車道: 62, 東九州自動車道: 63, 沖縄自動車道: 64, 京都縦貫自動車道: 65, 鹿児島道路: 66, 第二京阪道路: 67,
    第二神明道路: 68, 広島呉道路: 69, 本州四国連絡道路: 70, 首都高速道路: 71, 阪神高速道路: 72, 広島高速1号線: 73, 北九州高速4号線: 74,
    名阪国道: 75, 鳥取自動車道: 76, 深川留萌自動車道: 77, 旭川紋別自動車道: 78, 三陸自動車道: 79, 能越自動車道: 80,
    京奈和自動車道: 81, 北近畿豊岡自動車道: 82, 西広島バイパス: 83, 松永道路: 84, 姫路バイパス: 85, 日光宇都宮道路: 86, 播但連絡道路: 87,
    のと里山海道: 88
  }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  belongs_to :user
  belongs_to :pasa
  belongs_to :genre
  attachment :image

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search, word)
    @post = if search == 'forward_match'
              Post.where('title LIKE?', "#{word}%")
            elsif search == 'backward_match'
              Post.where('title LIKE?', "%#{word}")
            elsif search == 'perfect_match'
              Post.where(word.to_s)
            elsif search == 'partial_match'
              Post.where('title LIKE?', "%#{word}%")
            else
              Post.all
            end
  end

  validates :cleanliness, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }

  validates :congestion, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }

  validates :satisfaction, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }

  validates :pasa_id, presence: true
  validates :title, presence: true
  validates :opinion, presence: true
  validates :visit_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  attachment :profile_image

  validates :name, presence: true
  validates :nickname, presence: true
  validates :email, presence: true
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/pasas_controller.rb
class PasasController < ApplicationController
  def index
    @pasas = Pasa.page(params[:page]).reverse_order
  end

  def show
    @pasa = Pasa.find(params[:id])
    @posts = @pasa.posts
  end

  def autocomplete_facility
    # params[:cfacility]の値でPasa.facilityを前方一致検索、facility列だけ取り出し、nilと空文字を取り除いた配列
    facilities = Pasa.by_facility_like(autocomplete_params[:facility]).pluck(:facility).reject(&:blank?)
    render json: facilities
  end

  private

  def autocomplete_params
    params.permit(:facility)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pasas_helper.rb
module PasasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <p class="footer-text">
    © All rights reserved by pasa_navi.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <div class="container">
    <%= link_to image_tag("logo.png", class:"logo", size: "160x60"), root_path, data: {"turbolinks" => false} %>
    <nav class="pc-nav-list">
      <% if user_signed_in? %>
        <ul>
          <li><%= link_to posts_path, class: "btn-square-emboss" do %><i class="fas fa-list-alt"></i>投稿一覧<% end %></li>
          <li><%= link_to pasas_path, class: "btn-square-emboss" do %><i class="fas fa-store-alt"></i>pasa一覧<% end %></li>
          <li><%= link_to genres_path, class: "btn-square-emboss" do %><i class="fas fa-utensils"></i>ジャンル一覧<% end %></li>
          <li><%= link_to user_path(current_user.id), class: "btn-square-emboss" do %><i class="fas fa-user-alt"></i>マイページ<% end %></li>
          <li><%= link_to destroy_user_session_path, method: :delete , class: "btn-square-emboss" do%><i class="fas fa-sign-out-alt"></i>ログアウト<% end %></li>
        </ul>
      <% else %>
        <ul>
          <li><%= link_to posts_path, class: "btn-square-emboss" do %><i class="fas fa-list-alt"></i>投稿一覧<% end %></li>
          <li><%= link_to pasas_path, class: "btn-square-emboss" do %><i class="fas fa-store-alt"></i>pasa一覧<% end %></li>
          <li><%= link_to genres_path, class: "btn-square-emboss" do %><i class="fas fa-utensils"></i>ジャンル一覧<% end %></li>
          <li><%= link_to new_user_session_path, class: "btn-square-emboss" do %><i class="fas fa-sign-in-alt"></i>ログイン<% end %></li>
          <li><%= link_to new_user_registration_path, class: "btn-square-emboss" do %><i class="fas fa-user-plus"></i>サインアップ<% end %></li>
        </ul>
      <% end %>
    </nav>
    
    <!--レスポンシブハンバーガーメニュー-->
    <div class="hamburger">
      <div class="icon">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
    
    <nav class="smaho-nav-list">
      <% if user_signed_in? %>
        <ul>
          <li><%= link_to posts_path, class: "btn-square-emboss" do %><i class="fas fa-list-alt"></i>投稿一覧<% end %></li>
          <li><%= link_to pasas_path, class: "btn-square-emboss" do %><i class="fas fa-store-alt"></i>pasa一覧<% end %></li>
          <li><%= link_to genres_path, class: "btn-square-emboss" do %><i class="fas fa-utensils"></i>ジャンル一覧<% end %></li>
          <li><%= link_to user_path(current_user.id), class: "btn-square-emboss" do %><i class="fas fa-user-alt"></i>マイページ<% end %></li>
          <li><%= link_to destroy_user_session_path, method: :delete , class: "btn-square-emboss" do%><i class="fas fa-sign-out-alt"></i>ログアウト<% end %></li>
        </ul>
      <% else %>
        <ul>
          <li><%= link_to posts_path, class: "btn-square-emboss" do %><i class="fas fa-list-alt"></i>投稿一覧<% end %></li>
          <li><%= link_to pasas_path, class: "btn-square-emboss" do %><i class="fas fa-store-alt"></i>pasa一覧<% end %></li>
          <li><%= link_to genres_path, class: "btn-square-emboss" do %><i class="fas fa-utensils"></i>ジャンル一覧<% end %></li>
          <li><%= link_to new_user_session_path, class: "btn-square-emboss" do %><i class="fas fa-sign-in-alt"></i>ログイン<% end %></li>
          <li><%= link_to new_user_registration_path, class: "btn-square-emboss" do %><i class="fas fa-user-plus"></i>サインアップ<% end %></li>
        </ul>
      <% end %>
    </nav>
    
  </div>
</header>

<!--ハンバーガーメニューのJavaScript-->
<script>
  $('.hamburger').on('click', function(){
      $('.icon').toggleClass('close');
      $('.smaho-nav-list').slideToggle();
  });
</script>

<!--検索機能-->
<div class="search m-3">
  <%= form_tag(search_path, method: :get) do %>
    <!--rangeというparamsに[[]]の中身たちを収納-->
　　<%= select_tag 'range' ,options_for_select([['---選択してください---', ''], ['PA/SA名', '1'], ['投稿タイトル', '2']]) %>
    <!--searchというparamsに[[]]の中身たちを収納-->
 　　<%= select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
 　  <!--テキストボックスを作成し、"word"というパラメータ名で渡す-->
 　　<%= text_field_tag (:word) %>
    <%= button_tag :type => "submit", :class =>"btn btn-default btn-s-md" do %>
      <i class="fa fa-search"></i>検索
    <% end %>
  <% end %>
</div>

<div class="new-post-frame">
  <% if user_signed_in? %>
    <div class="new-post-create">
      <%= link_to new_post_path, class: "new-post" do %><i class="fas fa-pen-nib"></i>投稿を作成する<% end %>
    </div>
  <% else %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PasaNavi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/6d1adad93a.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Reggae+One&family=RocknRoll+One&display=swap" rel="stylesheet">
  </head>
  <body>
    
    
    <%= yield %>
  </body>
</html>